version: 0.2

phases:
  pre_build:
    commands:
      - echo "Updating instance and installing dependencies..."
      - sudo yum update -y
      - sudo yum install -y docker git
      - sudo service docker start || sudo dockerd &
      - git clone https://github.com/davidblack174/react-nodejs-example.git
      - cd react-nodejs-example
      - echo "Dependencies installed successfully!"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t react-nodejs .
      - echo "Docker image built successfully!"

  post_build:
    commands:
      - echo "Running the new container with index.html..."
      - docker run -d -p 80:80 --name react-nodejs react-nodejs
      - echo "Generating imagedefinitions.json file..."
      - cd ..
      - printf '[{"name":"react-nodejs","imageUri":"react-nodejs"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "Deployment complete!"

artifacts:
  files:
    - imagedefinitions.json
