version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install -g npm@latest || npm install -g npm@8
  pre_build:
    commands:
      - echo Installing UI dependencies...
      - cd my-app && npm install
  build:
    commands:
      - echo Building UI...
      - cd my-app && npm run build
      - echo Installing API dependencies...
      - cd ../api && npm install
  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - my-app/build/**
    - api/**
    - Dockerfile
