version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing Docker..."
      - sudo yum update -y
      - sudo yum install -y docker
      - nohup dockerd > /tmp/dockerd.log 2>&1 &
      - sleep 10  # Give Docker time to start
      - sudo chmod 666 /var/run/docker.sock
      - docker --version

  build:
    commands:
      - echo "Building and running Docker image..."
      - cd my-app
      - docker build -t my-app .
      - docker save -o my-app.tar my-app  # Save Docker image as a tar file for upload

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
  name: my-app-artifacts
  s3-prefix: simplifify-it
