version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing Docker..."
      - sudo yum update -y
      - sudo yum install -y docker
      - nohup dockerd > /tmp/dockerd.log 2>&1 &
      - sleep 10  # Give Docker time to start
      - sudo chmod 666 /var/run/docker.sock
      - docker --version

  build:
    commands:
      - echo "Building and running Docker image..."
      - ls -l  # Debugging: Check if Dockerfile exists
      - docker build -t my-app -f ./Dockerfile . 

  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 cp my-app.tar s3://your-s3-bucket-name/

artifacts:
  files:
    - my-app.tar
  discard-paths: no
  name: my-app-artifacts

cache:
  paths:
    - '/root/.docker/**'

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
