version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing Docker..."
      - sudo yum update -y
      - sudo yum install -y docker
      - sudo systemctl docker start
      - sudo usermod -a -G docker ec2-user
      - sudo chmod 666 /var/run/docker.sock
      - docker --version

  pre_build:
    commands:
      - echo "Ensuring Docker is running..."
      - systemctl docker status

  build:
    commands:
      - echo "Building and running Docker image..."
      - docker build -t my-app .
      - docker run -p 80:80 my-app

artifacts:
  files:
    - '**/*'
