apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: 528757791414.dkr.ecr.eu-west-1.amazonaws.com/<your-repo-name>:<tag>
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret
